<?
//Array so_sanh
$array_capbac = array("" => "Vui lòng chọn",
                      1 => "Mới Tốt Nghiệp",
                      2 => "Nhân viên",
                      6 => "Thực tập sinh",
                      3 => "Trưởng Nhóm",
                      4 => "Trưởng Phòng",
                      5 => "Giám Đốc và Cấp Cao Hơn",
                      );
$array_hinh_thuc = array(1=>"Toàn thời gian cố định",
                            2=>"Toàn thời gian tạm thời",
                            3=>"Bán thời gian",
                            4=>"Bán thời gian tạm thời",
                            5=>"Hợp đồng",
                            6=>"Khác");
$array_ngoai_ngu = array(1=>"Tiếng Anh",
                         2=>"Tiếng Nhật",
                         3=>"Tiếng Pháp",
                         4=>"Tiếng Trung",
                         5=>"Tiếng Nga",
                         6=>"Tiếng Đức",
                         7=>"Tiếng Ý",
                         8=>"Tiếng Ả Rập",
                        9=>"Tiếng Hàn");
$array_kha = array(0=>"Chưa cập nhật",
                   1=>"Tốt",
                   2=>"Khá",
                   3=>"Trung Bình",
                   4=>"Kém");
$array_xl = array(""=>"Chưa cập nhật",
                   5=>"Không bằng cấp",
                   1=>"Yếu",
                   2=>"Trung bình",
                   3=>"Khá",
                   4=>"Giỏi");
$array_gioi_tinh = array(0=>"Không yêu cầu",
                         1=>"Nam",
                         2=>"Nữ");
$array_gioi_tinh_tt = array( 
                            "" => 'Chọn giới tính',
                            1 => 'Nam',
                            2 => 'Nữ',
                            3 => 'Khác'
);
$array_hoc_van =   array(    ""=>"Không yêu cầu", 
                             7=>"Đại học",
                             5=>"Cao đẳng",
                             1=>"PTCS",
                             2=>"Trung học",
                             3=>"Chứng chỉ",
                             4=>"Trung cấp",
                             6=>"Cử nhân",
                             8=>"Thạc sĩ",
                             9=>"Thạc sĩ Nghệ thuật",
                             10=>"Thạc sĩ Thương mại",
                             11=>"Thạc sĩ Khoa học",
                             12=>"Thạc sĩ Kiến trúc",
                             13=>"Thạc sĩ QTKD",
                             14=>"Thạc sĩ Kỹ thuật ứng dụng",
                             15=>"Thạc sĩ Luật",
                             16=>"Thạc sĩ Y học",
                             17=>"Thạc sĩ Dược phẩm",
                             18=>"Tiến sĩ",
                             19=>"Khác");

$array_hoc_van_uv =   array( ""=>"Chọn bằng cấp", 
                             7=>"Đại học",
                             5=>"Cao đẳng",
                             1=>"PTCS",
                             2=>"Trung học",
                             3=>"Chứng chỉ",
                             4=>"Trung cấp",
                             6=>"Cử nhân",
                             8=>"Thạc sĩ",
                             9=>"Thạc sĩ Nghệ thuật",
                             10=>"Thạc sĩ Thương mại",
                             11=>"Thạc sĩ Khoa học",
                             12=>"Thạc sĩ Kiến trúc",
                             13=>"Thạc sĩ QTKD",
                             14=>"Thạc sĩ Kỹ thuật ứng dụng",
                             15=>"Thạc sĩ Luật",
                             16=>"Thạc sĩ Y học",
                             17=>"Thạc sĩ Dược phẩm",
                             18=>"Tiến sĩ",
                             19=>"Khác");
$array_kinh_nghiem =   array(   0 => "Chưa có kinh nghiệm",
                                1 => "0 - 1 năm kinh nghiệm",
                                2 => "1 - 2 năm kinh nghiệm",
                                3 => "2 - 5 năm kinh nghiệm",
                                4 => "5 - 10 năm kinh nghiệm",
                                5 =>"Hơn 10 năm kinh nghiệm");
$array_kinh_nghiem_uv = array(  "" => "Chọn kinh nghiệm",
                                0 => "Chưa có kinh nghiệm",
                                1 => "Dưới 1 năm",
                                2 => "1 năm",
                                3 => "2 năm",
                                4 => "3 năm",
                                5 => "4 năm",
                                6 => "5 năm",
                                7 => "Trên 5 năm",);
$array_cach_nop = array(1=>"Nộp trực tuyến",
                        2=>"Gửi kèm File",
                        3=>"Trực tiếp");
$array_muc_luong = array(''=>"Chọn mức lương",
                         1=>"Thỏa thuận",
                         2=>"1 - 3 triệu",
                         3=>"3 - 5 triệu",
                         4=>"5 - 7 triệu",
                         5=>"7 - 10 triệu",
                         6=>"10 - 15 triệu",
                         7=>"15 - 20 triệu",
                         8=>"20 - 30 triệu",
                         9=>"Trên 30 triệu");
$array_muc_luong2 = array(0=>"000000",
                         1=>"000000",
                         2=>"1000000",
                         3=>"3000000",
                         4=>"5000000",
                         5=>"7000000",
                         6=>"10000000",
                         7=>"15000000",
                         8=>"20000000",
                         9=>"30000000");
$array_do_tuoi = array(  0=>"Không yêu cầu",
                         1=>"Dưới 18 tuổi",
                         2=>"18 - 24 tuổi",
                         3=>"25 - 29 tuổi",
                         4=>"30 - 34 tuổi",
                         5=>"35 - 39 tuổi",
                         6=>"40 - 44 tuổi");
$array_quy_mo = array(   0=>"Chọn quy mô",
                         1=>"Ít hơn 10 nhân viên",
                         2=>"Từ 10 - 24 nhân viên",
                         3=>"Từ 25 - 99 nhân viên",
                         4=>"Từ 100 - 499 nhân viên",
                         5=>"Từ 500 - 999 nhân viên",
                         6=>"Trên 1000 nhân viên");
$array_quy_mo_com = array(1=>"Dưới 20 nhân viên",
                         2=>"20 - 50 nhân viên",
                         3=>"50 - 100 nhân viên",
                         4=>"100 - 300 nhân viên",
                         5=>"300 - 1000 nhân viên",
                         6=>"1000 - 3000 nhân viên",
                         7=>"Trên 3000 nhân viên");
$array_loai_hinh = array(1=>"Doanh nghiệp nhà nước",
                         2=>"Công ty Nước Ngoài",
                         3=>"Công ty Cổ Phần",
                         4=>"Công ty TNHH",
                         5=>"Công ty Đại Chúng",
                         6=>"Công ty Tư Nhân",
                         7=>"Công ty Hợp Danh");
$array_ngon_ngu = array(""=>"Chọn ngôn ngữ",
                         1=>"Tiếng Anh",
                         2=>"Tiếng Pháp",
                         3=>"Tiếng Nga",
                         4=>"Tiếng Hàn",
                         5=>"Tiếng Trung",
                         6=>"Tiếng Nhật");
$array_hon_nhan = array(""=>"Chọn tình trạng hôn nhân",
                        1=>"Độc thân",
                        2=>"Đã lập gia đình");
$array_muctieu = array(
                    1=>"Mong muốn tìm được chỗ làm ổn định, lâu dài",
                    2=>"Mong muốn tìm được chỗ làm có cơ hội thăng tiến tốt",
                    3=>"Mong muốn tìm được chỗ làm có mức lương tốt",
                    4=>"Mong muốn tìm được nơi có cơ hội cống hiến bản thân tốt",
                    5=>"Mong muốn được làm việc trong môi trường chuyên nghiệp"
                );
$array_kinang = array(
                    1 => "Biết lắng nghe tiếp thu ý kiến của đồng nghiệp và cấp trên",
                    2 => "Chăm chỉ, chịu khó tìm hiểu các vấn đề trong công việc và cuộc sống",
                    3 => "Tinh thần trách nhiệm trong công việc",
                    4 => "Chịu được áp lực trong công việc",
                    5 => "Hòa đồng, vui vẻ với đồng nghiệp"
                );
$array_bang_gia = array(0=>"Chọn gói",
                         1=>"GHIM TIN TRANG CHỦ BOX VIỆC LÀM HẤP DẪN",
                         2=>"GHIM TIN TRANG CHỦ BOX VIỆC LÀM TUYỂN GẤP",
                         3=>"GHIM TIN TRANG CHỦ BOX VIỆC LÀM LƯƠNG CAO",
                         4=>"GHIM TIN TRANG NGÀNH",
                         // 4=>"GHIM TIN TRANG CHỦ BOX THƯƠNG HIỆU",
                         5=>"LỌC HỒ SƠ",
                         // 7=>"BANNER TUYỂN DỤNG",
                         // 8=>"BIỂU TƯỢNG TĂNG CLICK",
                         // 9=>"TUYỂN DỤNG THUÊ (HEADHUNTER)"
                     );
?>